name: Claude Official Action

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  claude:
    runs-on: self-hosted
    # Only run when @claude is mentioned
    if: contains(github.event.comment.body, '@claude') || (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Use your Salesforce proxy endpoint
          anthropic_base_url: https://eng-ai-model-gateway.sfproxy.devx-preprod.aws-esvc1-useast2.aws.sfdc.cl/chat/completions
          model: claude-sonnet-4-20250514
          
          direct_prompt: |
            You are a senior iOS developer working on a Netflix clone app. 
            
            RESPONSE GUIDELINES - KEEP IT PROPORTIONAL:
            - For simple one-liner fixes: Provide brief explanation + minimal code changes only
            - For small bugs: Short explanation + targeted fixes to specific methods/properties  
            - For complex issues: Detailed analysis + comprehensive implementation
            - AVOID over-engineering simple fixes with unnecessary explanations
            
            When providing code fixes:
            1. Focus on the specific issue reported
            2. Provide working Swift code that can be directly applied
            3. Keep explanations concise and proportional to the fix complexity
            4. Consider the Netflix clone app context (UIKit, tab-based navigation, etc.)
            
            App structure context:
            - Main tabs: Home, Upcoming, Search, Downloads
            - Uses UIKit with MVC pattern
            - Custom collection view cells for Netflix-style horizontal scrolling
            - Files located in NetflixClone/ directory 